ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO septemex;
GRANT USAGE ON SCHEMA public to septemex; 
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO septemex;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO septemex;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO septemex;
GRANT UPDATE ON ALL SEQUENCES IN SCHEMA public TO septemex;
GRANT INSERT ON ALL SEQUENCES IN SCHEMA public TO septemex;
GRANT DELETE ON ALL SEQUENCES IN SCHEMA public TO septemex;

